export const state = () => ({
  totalPages: 100,
  infoCard: [
    {
      title: "Mulan",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/mulan.png"),
      isBig: true,
      id: 1,
    },
    {
      title: "Over the Moon",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/moon.png"),
      isBig: false,
    },
    {
      title: "Bacurau",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/bacurau.png"),
      isBig: false,
      id: 2,
    },
    {
      title: "The Midnight Sky",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/ceu.png"),
      isBig: true,
      id: 3,
    },
    {
      title: "Love And Monters",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/love.png"),
      isBig: true,
      id: 4,
    },
    {
      title: "Another Round",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/another.png"),
      isBig: false,
      id: 5,
    },
    {
      title: "Emma",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/emma.png"),
      isBig: false,
      id: 6,
    },
    {
      title: "The Trial",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/chicago.png"),
      isBig: true,
      id: 7,
    },
    {
      title: "Enet",
      infoYear: "2h20m • 2020",
      src: require("../assets/images/net.png"),
      isBig: true,
      id: 8,
    },
  ],
});
